### ISSUE TITLE
Grid height does not increase automatically...

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [PMSI-AlignAlytics/scrollgrid#1]
Am building a pagination control to display data in pages using scrollgrid. So for scrollgrid, it always holds only one page of data. As user presses respective page numbers in pagination control, an adapter is passed to scrollgrid's `data()` method wherein the adapter serves current page's data.

![image](https://cloud.githubusercontent.com/assets/1784880/9352506/681e752a-467f-11e5-8a9c-a41c7f8064c3.png)

Everything works fine except for one issue.

If the last page has less number of rows than the page-size, then the grid shrinks accordingly - which is the desired behavior.

![image](https://cloud.githubusercontent.com/assets/1784880/9352534/a322fe48-467f-11e5-942b-db6d4ea37a8f.png)

However, subsequently, if I move back to one of the other pages, then the grid retains the same (shrunken) size on display and shows a scrollbar to accommodate number of rows of page-size.

![image](https://cloud.githubusercontent.com/assets/1784880/9352554/c456772a-467f-11e5-8edb-4131acd0f94c.png)

Instead, I had expected it to display the table with all rows visible and no scrollbar.

Please let me know if this is something that can be fixed in scrollgrid. Or, is there a workaround / solution to this???

**Comment by johnkiernander** [comment]
Would you be able to put this in a jsFiddle?  I think the problem might be to do with the containing DOM but I'm not sure without testing it.

**Comment by nagarajanchinnasamy** [comment]
Hi John, sorry for the delay in responding... I have resolved this issue by deleting the current scrollgrid and creating a new scrollgrid for every page.
